export const StatusCode = {
	OK: 200,
	CREATED: 201,
	TOKEN_REFRESH: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	INTERNAL_SERVER_ERROR: 500,
};

export const PrivateType = {
	PUBLIC: `PUBLIC`,
	PRIVATE: `PRIVATE`,
	PRIVATE_AUTH: `PRIVATE_AUTH`,
};
